### ISSUE TITLE
Battery Level issue

### ISSUE THREAD

**Issue by yushtsai** [sonyxperiadev/device-sony-poplar#34]
The battery level always shows 20%.
incorrect battery level
Can the problem be solved?

**Comment by waltercool** [comment]
You should report bug issues here: https://github.com/sonyxperiadev/bug_tracker/issues

Also, fixing battery level is quite easy, and happens when you change your firmware version. Just make multiple times power + vol up for 10s until shakes 3 times

**Comment by jerpelea** [comment]
what firmware do you have on your phone ?
you can check with 
fastboot getvar --all

**Comment by jerpelea** [comment]
please use the bug tracker to report issues!
